// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ShootingStarsAndStarsBackgroundDemo } from "@/app/components/Shooting"; 

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//   className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 relative`}
// >

//         {/* 👇 Full-page animated background behind everything */}
//         <ShootingStarsAndStarsBackgroundDemo />

//         {/* 👇 Main content stays above the background */}
//         <main className="relative z-10">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ShootingStarsAndStarsBackgroundDemo } from "./components/Shooting";

// ✅ Correctly load the fonts
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata: Metadata = {
  title: "Your Site",
  description: "Your description",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-neutral-900 relative">
        {/* 👇 Full-page animated background behind everything */}
        <ShootingStarsAndStarsBackgroundDemo />

        {/* 👇 Main content stays above the background */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
